#!/usr/bin/env php
<?php
/*
 * 2022 Client Name
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License 3.0 (AFL-3.0).
 * It is also available through the world-wide-web at this URL: https://opensource.org/licenses/AFL-3.0
 *
 * @author    PrestaShop partner
 * @copyright 2022 Client Name
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 */

$autoload1 = __DIR__.'/../vendor/autoload.php';
$autoload2 = __DIR__.'/../../../autoload.php';
if (file_exists($autoload1)) {
    require_once $autoload1;
} else {
    require_once $autoload2;
}

use AG\PSModuleUtils\Command\InitModuleCommand;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new InitModuleCommand());
$app->run();
